services:
  postgres:
    image: postgres:15-alpine
    container_name: astrolabe_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: astrolabe
      POSTGRES_PASSWORD: astrolabe
      POSTGRES_DB: astrolabe
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
